//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Cliente.LoanServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Loan", Namespace="http://schemas.datacontract.org/2004/07/LoanService.Models")]
    [System.SerializableAttribute()]
    public partial class Loan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookId {
            get {
                return this.BookIdField;
            }
            set {
                if ((this.BookIdField.Equals(value) != true)) {
                    this.BookIdField = value;
                    this.RaisePropertyChanged("BookId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoanServiceRef.ILoanService")]
    public interface ILoanService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/BorrowBook", ReplyAction="http://tempuri.org/ILoanService/BorrowBookResponse")]
        bool BorrowBook(int userId, int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/BorrowBook", ReplyAction="http://tempuri.org/ILoanService/BorrowBookResponse")]
        System.Threading.Tasks.Task<bool> BorrowBookAsync(int userId, int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/ReturnBook", ReplyAction="http://tempuri.org/ILoanService/ReturnBookResponse")]
        bool ReturnBook(int userId, int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/ReturnBook", ReplyAction="http://tempuri.org/ILoanService/ReturnBookResponse")]
        System.Threading.Tasks.Task<bool> ReturnBookAsync(int userId, int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/GetLoansByUser", ReplyAction="http://tempuri.org/ILoanService/GetLoansByUserResponse")]
        Libreria.Cliente.LoanServiceRef.Loan[] GetLoansByUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/GetLoansByUser", ReplyAction="http://tempuri.org/ILoanService/GetLoansByUserResponse")]
        System.Threading.Tasks.Task<Libreria.Cliente.LoanServiceRef.Loan[]> GetLoansByUserAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoanServiceChannel : Libreria.Cliente.LoanServiceRef.ILoanService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoanServiceClient : System.ServiceModel.ClientBase<Libreria.Cliente.LoanServiceRef.ILoanService>, Libreria.Cliente.LoanServiceRef.ILoanService {
        
        public LoanServiceClient() {
        }
        
        public LoanServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoanServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool BorrowBook(int userId, int bookId) {
            return base.Channel.BorrowBook(userId, bookId);
        }
        
        public System.Threading.Tasks.Task<bool> BorrowBookAsync(int userId, int bookId) {
            return base.Channel.BorrowBookAsync(userId, bookId);
        }
        
        public bool ReturnBook(int userId, int bookId) {
            return base.Channel.ReturnBook(userId, bookId);
        }
        
        public System.Threading.Tasks.Task<bool> ReturnBookAsync(int userId, int bookId) {
            return base.Channel.ReturnBookAsync(userId, bookId);
        }
        
        public Libreria.Cliente.LoanServiceRef.Loan[] GetLoansByUser(int userId) {
            return base.Channel.GetLoansByUser(userId);
        }
        
        public System.Threading.Tasks.Task<Libreria.Cliente.LoanServiceRef.Loan[]> GetLoansByUserAsync(int userId) {
            return base.Channel.GetLoansByUserAsync(userId);
        }
    }
}
